server:
  port: 2222

spring:
  application:
    name: distributed-lock-redis001
    version: 1.0.0.DEV
  # banner颜色生效，NEVER：禁用ANSI-colored输出（默认项） DETECT：会检查终端是否支持ANSI，是的话就采用彩色输出（推荐项）  ALWAYS：总是使用ANSI-colored格式输出，若终端不支持的时候，会有很多干扰信息，不推荐使用
  output:
    ansi:
      enabled: ALWAYS
  # banner内容
  banner:
    location: ["classpath:banner.txt", "file:./banner.txt"]
  redis:
    # redis 数据库索引
    database: 0
    # redis 服务地址
    host: 127.0.0.1
    # redis 服务连接端口
    port: 6379
    # redis 服务连接密码
    password:
    # redis 连接池配置
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）默认8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）默认-1
        max-wait: -1
        # 连接池最大空闲连接 默认8
        max-idle: 8
        # 连接池最小空闲连接 默认0
        min-idle: 0
